name: Python CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Simulating Deployment
      run: |
        echo "Iniciando deploy na infraestrutura da PUCPR..."
        echo "Copiando arquivos para o servidor de produção..."
        echo "Deploy finalizado com sucesso!"